name: flutter_neis
description: "Flutter에서 NEIS 교육정보 개방 포털을 쉽게 사용할 수 있게 해주는 패키지입니다."
version: 1.0.2

homepage: https://github.com/jinhyeon-dev/flutter_neis
repository: https://github.com/jinhyeon-dev/flutter_neis
issue_tracker: https://github.com/jinhyeon-dev/flutter_neis/issues

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true